from measures.db import get_areas
from measures.db import get_locations_by_area_id
from measures.db import get_categories_by_area_id
from measures.db import get_measures_by_location_id
from measures.db import get_avg_measurement_by_area_id
from measures.db import get_locations_count_by_area_id